Add regression tests for TSConfig (#8266)
* Upgrade prep: Improved regression tests for TSConfig (failing tests to fix)

* Fix compilation error "error TS2687: All declarations of 'name' must have identical modifiers."

* Fix bundle-css build errors related to an unexpected CWD

* Fix bundle-html build errors related to an unexpected CWD

* Fix bundle-locales build errors related to an unexpected CWD

* Remove jsdom from Jest config

* Fix error handling when firefox-nightly is not installed

* Fix error handling when karma config is not valid

* Fix Karma rollup build errors related to an unexpected CWD

* Increase heap memory limit for V8

* Give tests/inject its own test-util.ts since it's loaded in the browser

* Fix compilation of ./src when "composite" is true

* Move unit tests into their own directory; Organize jest config

* lint fix

* Exact versions in package.json

* Gitignore Node's profiler log files

* Exact versions in package.json II

* Alphabetical package.json scripts

* Remove dev cruft