Fix compilation error "error TS2687: All declarations of 'name' must have identical modifiers."
The error stemmed from a conflict between `@types/filesystem` and the TS dom lib and looked like this:

```
 % tsc --build src
../dev/node_modules/typescript/lib/lib.dom.d.ts:5074:14 - error TS2687: All declarations of 'name' must have identical modifiers.
../dev/node_modules/typescript/lib/lib.dom.d.ts:5075:14 - error TS2687: All declarations of 'root' must have identical modifiers.
node_modules/@types/filesystem/index.d.ts:104:5 - error TS2687: All declarations of 'name' must have identical modifiers.
node_modules/@types/filesystem/index.d.ts:109:5 - error TS2687: All declarations of 'root' must have identical modifiers.
node_modules/@types/filesystem/index.d.ts:109:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'root' must be of type 'FileSystemDirectoryEntry', but here has type 'DirectoryEntry'.
node_modules/@types/filesystem/index.d.ts:365:11 - error TS2304: Cannot find name 'DOMError'.
```